/* Copyright (c) 2017-2025, Hans Erik Thrane */

#include <catch2/catch_all.hpp>

#include "wsapi_parser_tester.hpp"

using namespace roq;
using namespace roq::binance_futures;

using namespace std::literals;

using namespace Catch::literals;

using value_type = json::WSAPIAccountPosition;

TEST_CASE("fapi", "[json_wsapi_account_position]") {
  auto message = R"({)"
                 R"("id":"g4QeAAcAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",)"
                 R"("status":200,)"
                 R"("result":[{)"
                 R"("symbol":"SNTUSDT",)"
                 R"("positionAmt":"0",)"
                 R"("entryPrice":"0.0",)"
                 R"("breakEvenPrice":"0.0",)"
                 R"("markPrice":"0.00000000",)"
                 R"("unRealizedProfit":"0.00000000",)"
                 R"("liquidationPrice":"0",)"
                 R"("leverage":"20",)"
                 R"("maxNotionalValue":"25000",)"
                 R"("marginType":"cross",)"
                 R"("isolatedMargin":"0.00000000",)"
                 R"("isAutoAddMargin":"false",)"
                 R"("positionSide":"BOTH",)"
                 R"("notional":"0",)"
                 R"("isolatedWallet":"0",)"
                 R"("updateTime":0,)"
                 R"("isolated":false,)"
                 R"("adlQuantile":0)"
                 R"(},{)"
                 R"("symbol":"SUSHIUSDT",)"
                 R"("positionAmt":"0",)"
                 R"("entryPrice":"0.0",)"
                 R"("breakEvenPrice":"0.0",)"
                 R"("markPrice":"0.00000000",)"
                 R"("unRealizedProfit":"0.00000000",)"
                 R"("liquidationPrice":"0",)"
                 R"("leverage":"20",)"
                 R"("maxNotionalValue":"100000",)"
                 R"("marginType":"cross",)"
                 R"("isolatedMargin":"0.00000000",)"
                 R"("isAutoAddMargin":"false",)"
                 R"("positionSide":"BOTH",)"
                 R"("notional":"0",)"
                 R"("isolatedWallet":"0",)"
                 R"("updateTime":0,)"
                 R"("isolated":false,)"
                 R"("adlQuantile":0)"
                 R"(},{)"
                 R"("symbol":"SUNUSDT",)"
                 R"("positionAmt":"0",)"
                 R"("entryPrice":"0.0",)"
                 R"("breakEvenPrice":"0.0",)"
                 R"("markPrice":"0.00000000",)"
                 R"("unRealizedProfit":"0.00000000",)"
                 R"("liquidationPrice":"0",)"
                 R"("leverage":"20",)"
                 R"("maxNotionalValue":"30000",)"
                 R"("marginType":"cross",)"
                 R"("isolatedMargin":"0.00000000",)"
                 R"("isAutoAddMargin":"false",)"
                 R"("positionSide":"BOTH",)"
                 R"("notional":"0",)"
                 R"("isolatedWallet":"0",)"
                 R"("updateTime":0,)"
                 R"("isolated":false,)"
                 R"("adlQuantile":0)"
                 R"(})"
                 R"(],)"
                 R"("rateLimits":[{)"
                 R"("rateLimitType":"REQUEST_WEIGHT",)"
                 R"("interval":"MINUTE",)"
                 R"("intervalNum":1,)"
                 R"("limit":2400,)"
                 R"("count":13)"
                 R"(})"
                 R"(])"
                 R"(})"sv;
  auto helper = [](value_type const &obj) {
    CHECK(obj.id == "g4QeAAcAAAAAAAAAAAAAAAAAAAAAAAAAAAAA");
    CHECK(obj.status == 200);
    REQUIRE(std::size(obj.result) == 3);
    REQUIRE(std::size(obj.rate_limits) == 1);
  };
  WSAPIParserTester<value_type>::dispatch(helper, message, 8192, 1);
}

TEST_CASE("dapi", "[json_wsapi_account_position]") {
  auto message = R"({)"
                 R"("id":"g4QeAAcAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",)"
                 R"("status":200,)"
                 R"("result":[{)"
                 R"("symbol":"SOLUSD_260327",)"
                 R"("positionAmt":"0",)"
                 R"("entryPrice":"0.00000000",)"
                 R"("markPrice":"0.00000000",)"
                 R"("unRealizedProfit":"0.00000000",)"
                 R"("liquidationPrice":"0",)"
                 R"("leverage":"5",)"
                 R"("maxQty":"8000",)"
                 R"("marginType":"cross",)"
                 R"("isolatedMargin":"0.00000000",)"
                 R"("isAutoAddMargin":"false",)"
                 R"("positionSide":"BOTH",)"
                 R"("notionalValue":"0",)"
                 R"("isolatedWallet":"0",)"
                 R"("updateTime":0,)"
                 R"("breakEvenPrice":"0.00000000")"
                 R"(},{)"
                 R"("symbol":"BNBUSD_260327",)"
                 R"("positionAmt":"0",)"
                 R"("entryPrice":"0.00000000",)"
                 R"("markPrice":"0.00000000",)"
                 R"("unRealizedProfit":"0.00000000",)"
                 R"("liquidationPrice":"0",)"
                 R"("leverage":"5",)"
                 R"("maxQty":"20000",)"
                 R"("marginType":"cross",)"
                 R"("isolatedMargin":"0.00000000",)"
                 R"("isAutoAddMargin":"false",)"
                 R"("positionSide":"BOTH",)"
                 R"("notionalValue":"0",)"
                 R"("isolatedWallet":"0",)"
                 R"("updateTime":0,)"
                 R"("breakEvenPrice":"0.00000000")"
                 R"(},{)"
                 R"("symbol":"UNIUSD_PERP",)"
                 R"("positionAmt":"0",)"
                 R"("entryPrice":"0.00000000",)"
                 R"("markPrice":"0.00000000",)"
                 R"("unRealizedProfit":"0.00000000",)"
                 R"("liquidationPrice":"0",)"
                 R"("leverage":"5",)"
                 R"("maxQty":"30000",)"
                 R"("marginType":"cross",)"
                 R"("isolatedMargin":"0.00000000",)"
                 R"("isAutoAddMargin":"false",)"
                 R"("positionSide":"BOTH",)"
                 R"("notionalValue":"0",)"
                 R"("isolatedWallet":"0",)"
                 R"("updateTime":0,)"
                 R"("breakEvenPrice":"0.00000000")"
                 R"(},{)"
                 R"("symbol":"OPUSD_PERP",)"
                 R"("positionAmt":"0",)"
                 R"("entryPrice":"0.00000000",)"
                 R"("markPrice":"0.00000000",)"
                 R"("unRealizedProfit":"0.00000000",)"
                 R"("liquidationPrice":"0",)"
                 R"("leverage":"5",)"
                 R"("maxQty":"300000",)"
                 R"("marginType":"cross",)"
                 R"("isolatedMargin":"0.00000000",)"
                 R"("isAutoAddMargin":"false",)"
                 R"("positionSide":"BOTH",)"
                 R"("notionalValue":"0",)"
                 R"("isolatedWallet":"0",)"
                 R"("updateTime":0,)"
                 R"("breakEvenPrice":"0.00000000")"
                 R"(})"
                 R"(],)"
                 R"("rateLimits":[{)"
                 R"("rateLimitType":"REQUEST_WEIGHT",)"
                 R"("interval":"MINUTE",)"
                 R"("intervalNum":1,)"
                 R"("limit":2400,)"
                 R"("count":31)"
                 R"(})"
                 R"(])"
                 R"(})"sv;
  auto helper = [](value_type const &obj) {
    CHECK(obj.id == "g4QeAAcAAAAAAAAAAAAAAAAAAAAAAAAAAAAA");
    CHECK(obj.status == 200);
    REQUIRE(std::size(obj.result) == 4);
    REQUIRE(std::size(obj.rate_limits) == 1);
  };
  WSAPIParserTester<value_type>::dispatch(helper, message, 8192, 1);
}
