/* Copyright (c) 2017-2025, Hans Erik Thrane */

#include <catch2/catch_all.hpp>

#include "wsapi_parser_tester.hpp"

using namespace roq;
using namespace roq::binance_futures;

using namespace std::literals;

using namespace Catch::literals;

using value_type = json::WSAPIAccountStatus;

TEST_CASE("fapi", "[json_wsapi_account_status]") {
  auto message = R"({)"
                 R"("id":"hYQeAAYAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",)"
                 R"("status":200,)"
                 R"("result":{)"
                 R"("feeTier":4,)"
                 R"("canTrade":true,)"
                 R"("canDeposit":true,)"
                 R"("canWithdraw":true,)"
                 R"("feeBurn":true,)"
                 R"("tradeGroupId":-1,)"
                 R"("updateTime":0,)"
                 R"("multiAssetsMargin":false,)"
                 R"("totalInitialMargin":"0.00000000",)"
                 R"("totalMaintMargin":"0.00000000",)"
                 R"("totalWalletBalance":"747.92226447",)"
                 R"("totalUnrealizedProfit":"0.00000000",)"
                 R"("totalMarginBalance":"747.92226447",)"
                 R"("totalPositionInitialMargin":"0.00000000",)"
                 R"("totalOpenOrderInitialMargin":"0.00000000",)"
                 R"("totalCrossWalletBalance":"747.92226447",)"
                 R"("totalCrossUnPnl":"0.00000000",)"
                 R"("availableBalance":"747.92226447",)"
                 R"("maxWithdrawAmount":"747.92226447",)"
                 R"("assets":[{)"
                 R"("asset":"FDUSD",)"
                 R"("walletBalance":"0.00000000",)"
                 R"("unrealizedProfit":"0.00000000",)"
                 R"("marginBalance":"0.00000000",)"
                 R"("maintMargin":"0.00000000",)"
                 R"("initialMargin":"0.00000000",)"
                 R"("positionInitialMargin":"0.00000000",)"
                 R"("openOrderInitialMargin":"0.00000000",)"
                 R"("maxWithdrawAmount":"0.00000000",)"
                 R"("crossWalletBalance":"0.00000000",)"
                 R"("crossUnPnl":"0.00000000",)"
                 R"("availableBalance":"0.00000000",)"
                 R"("marginAvailable":true,)"
                 R"("updateTime":0)"
                 R"(},{)"
                 R"("asset":"LDUSDT",)"
                 R"("walletBalance":"0.00000000",)"
                 R"("unrealizedProfit":"0.00000000",)"
                 R"("marginBalance":"0.00000000",)"
                 R"("maintMargin":"0.00000000",)"
                 R"("initialMargin":"0.00000000",)"
                 R"("positionInitialMargin":"0.00000000",)"
                 R"("openOrderInitialMargin":"0.00000000",)"
                 R"("maxWithdrawAmount":"0.00000000",)"
                 R"("crossWalletBalance":"0.00000000",)"
                 R"("crossUnPnl":"0.00000000",)"
                 R"("availableBalance":"0.00000000",)"
                 R"("marginAvailable":true,)"
                 R"("updateTime":0)"
                 R"(},{)"
                 R"("asset":"USDC",)"
                 R"("walletBalance":"375.00000000",)"
                 R"("unrealizedProfit":"0.00000000",)"
                 R"("marginBalance":"375.00000000",)"
                 R"("maintMargin":"0.00000000",)"
                 R"("initialMargin":"0.00000000",)"
                 R"("positionInitialMargin":"0.00000000",)"
                 R"("openOrderInitialMargin":"0.00000000",)"
                 R"("maxWithdrawAmount":"375.00000000",)"
                 R"("crossWalletBalance":"375.00000000",)"
                 R"("crossUnPnl":"0.00000000",)"
                 R"("availableBalance":"375.00000000",)"
                 R"("marginAvailable":true,)"
                 R"("updateTime":1764103550800)"
                 R"(})"
                 R"(],)"
                 R"("positions":[{)"
                 R"("symbol":"SNTUSDT",)"
                 R"("initialMargin":"0",)"
                 R"("maintMargin":"0",)"
                 R"("unrealizedProfit":"0.00000000",)"
                 R"("positionInitialMargin":"0",)"
                 R"("openOrderInitialMargin":"0",)"
                 R"("leverage":"20",)"
                 R"("isolated":false,)"
                 R"("entryPrice":"0.0",)"
                 R"("breakEvenPrice":"0.0",)"
                 R"("maxNotional":"25000",)"
                 R"("positionSide":"BOTH",)"
                 R"("positionAmt":"0",)"
                 R"("notional":"0",)"
                 R"("isolatedWallet":"0",)"
                 R"("updateTime":0,)"
                 R"("bidNotional":"0",)"
                 R"("askNotional":"0")"
                 R"(},{)"
                 R"("symbol":"SUNUSDT",)"
                 R"("initialMargin":"0",)"
                 R"("maintMargin":"0",)"
                 R"("unrealizedProfit":"0.00000000",)"
                 R"("positionInitialMargin":"0",)"
                 R"("openOrderInitialMargin":"0",)"
                 R"("leverage":"20",)"
                 R"("isolated":false,)"
                 R"("entryPrice":"0.0",)"
                 R"("breakEvenPrice":"0.0",)"
                 R"("maxNotional":"30000",)"
                 R"("positionSide":"BOTH",)"
                 R"("positionAmt":"0",)"
                 R"("notional":"0",)"
                 R"("isolatedWallet":"0",)"
                 R"("updateTime":0,)"
                 R"("bidNotional":"0",)"
                 R"("askNotional":"0")"
                 R"(})"
                 R"(])"
                 R"(},)"
                 R"("rateLimits":[{)"
                 R"("rateLimitType":"REQUEST_WEIGHT",)"
                 R"("interval":"MINUTE",)"
                 R"("intervalNum":1,)"
                 R"("limit":2400,)"
                 R"("count":15)"
                 R"(})"
                 R"(])"
                 R"(})"sv;
  auto helper = [](value_type const &obj) {
    CHECK(obj.id == "hYQeAAYAAAAAAAAAAAAAAAAAAAAAAAAAAAAA");
    CHECK(obj.status == 200);
    CHECK(obj.result.fee_tier == 4);
    CHECK(obj.result.can_trade == true);
    CHECK(obj.result.can_deposit == true);
    CHECK(obj.result.can_withdraw == true);
    CHECK(obj.result.update_time == 0ms);
    REQUIRE(std::size(obj.result.assets) == 3);
    REQUIRE(std::size(obj.result.positions) == 2);
    REQUIRE(std::size(obj.rate_limits) == 1);
  };
  WSAPIParserTester<value_type>::dispatch(helper, message, 8192, 2);
}

TEST_CASE("dapi", "[json_wsapi_account_status]") {
  auto message = R"({)"
                 R"("id":"hYQeAAYAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",)"
                 R"("status":200,)"
                 R"("result":{)"
                 R"("feeTier":4,)"
                 R"("canTrade":true,)"
                 R"("canDeposit":true,)"
                 R"("canWithdraw":true,)"
                 R"("updateTime":0,)"
                 R"("assets":[{)"
                 R"("asset":"AVAX",)"
                 R"("walletBalance":"0.00000000",)"
                 R"("unrealizedProfit":"0.00000000",)"
                 R"("marginBalance":"0.00000000",)"
                 R"("maintMargin":"0.00000000",)"
                 R"("initialMargin":"0.00000000",)"
                 R"("positionInitialMargin":"0.00000000",)"
                 R"("openOrderInitialMargin":"0.00000000",)"
                 R"("maxWithdrawAmount":"0.00000000",)"
                 R"("crossWalletBalance":"0.00000000",)"
                 R"("crossUnPnl":"0.00000000",)"
                 R"("availableBalance":"0.00000000",)"
                 R"("updateTime":0)"
                 R"(},{)"
                 R"("asset":"EOS",)"
                 R"("walletBalance":"0.00000000",)"
                 R"("unrealizedProfit":"0.00000000",)"
                 R"("marginBalance":"0.00000000",)"
                 R"("maintMargin":"0.00000000",)"
                 R"("initialMargin":"0.00000000",)"
                 R"("positionInitialMargin":"0.00000000",)"
                 R"("openOrderInitialMargin":"0.00000000",)"
                 R"("maxWithdrawAmount":"0.00000000",)"
                 R"("crossWalletBalance":"0.00000000",)"
                 R"("crossUnPnl":"0.00000000",)"
                 R"("availableBalance":"0.00000000",)"
                 R"("updateTime":0)"
                 R"(},{)"
                 R"("asset":"FIL",)"
                 R"("walletBalance":"0.00000000",)"
                 R"("unrealizedProfit":"0.00000000",)"
                 R"("marginBalance":"0.00000000",)"
                 R"("maintMargin":"0.00000000",)"
                 R"("initialMargin":"0.00000000",)"
                 R"("positionInitialMargin":"0.00000000",)"
                 R"("openOrderInitialMargin":"0.00000000",)"
                 R"("maxWithdrawAmount":"0.00000000",)"
                 R"("crossWalletBalance":"0.00000000",)"
                 R"("crossUnPnl":"0.00000000",)"
                 R"("availableBalance":"0.00000000",)"
                 R"("updateTime":0)"
                 R"(})"
                 R"(],)"
                 R"("positions":[{)"
                 R"("symbol":"SOLUSD_260327",)"
                 R"("initialMargin":"0",)"
                 R"("maintMargin":"0",)"
                 R"("unrealizedProfit":"0.00000000",)"
                 R"("positionInitialMargin":"0",)"
                 R"("openOrderInitialMargin":"0",)"
                 R"("leverage":"5",)"
                 R"("isolated":false,)"
                 R"("positionSide":"BOTH",)"
                 R"("entryPrice":"0.00000000",)"
                 R"("maxQty":"8000",)"
                 R"("notionalValue":"0",)"
                 R"("isolatedWallet":"0",)"
                 R"("updateTime":0,)"
                 R"("positionAmt":"0",)"
                 R"("breakEvenPrice":"0.00000000")"
                 R"(},{)"
                 R"("symbol":"SOLUSD_260327",)"
                 R"("initialMargin":"0",)"
                 R"("maintMargin":"0",)"
                 R"("unrealizedProfit":"0.00000000",)"
                 R"("positionInitialMargin":"0",)"
                 R"("openOrderInitialMargin":"0",)"
                 R"("leverage":"5",)"
                 R"("isolated":false,)"
                 R"("positionSide":"LONG",)"
                 R"("entryPrice":"0.00000000",)"
                 R"("maxQty":"8000",)"
                 R"("notionalValue":"0",)"
                 R"("isolatedWallet":"0",)"
                 R"("updateTime":0,)"
                 R"("positionAmt":"0",)"
                 R"("breakEvenPrice":"0.00000000")"
                 R"(},{)"
                 R"("symbol":"OPUSD_PERP",)"
                 R"("initialMargin":"0",)"
                 R"("maintMargin":"0",)"
                 R"("unrealizedProfit":"0.00000000",)"
                 R"("positionInitialMargin":"0",)"
                 R"("openOrderInitialMargin":"0",)"
                 R"("leverage":"5",)"
                 R"("isolated":false,)"
                 R"("positionSide":"SHORT",)"
                 R"("entryPrice":"0.00000000",)"
                 R"("maxQty":"300000",)"
                 R"("notionalValue":"0",)"
                 R"("isolatedWallet":"0",)"
                 R"("updateTime":0,)"
                 R"("positionAmt":"0",)"
                 R"("breakEvenPrice":"0.00000000")"
                 R"(})"
                 R"(])"
                 R"(},)"
                 R"("rateLimits":[{)"
                 R"("rateLimitType":"REQUEST_WEIGHT",)"
                 R"("interval":"MINUTE",)"
                 R"("intervalNum":1,)"
                 R"("limit":2400,)"
                 R"("count":26)"
                 R"(})"
                 R"(])"
                 R"(})"sv;
  auto helper = [](value_type const &obj) {
    CHECK(obj.id == "hYQeAAYAAAAAAAAAAAAAAAAAAAAAAAAAAAAA");
    CHECK(obj.status == 200);
    CHECK(obj.result.fee_tier == 4);
    CHECK(obj.result.can_trade == true);
    CHECK(obj.result.can_deposit == true);
    CHECK(obj.result.can_withdraw == true);
    CHECK(obj.result.update_time == 0ms);
    REQUIRE(std::size(obj.result.assets) == 3);
    REQUIRE(std::size(obj.result.positions) == 3);
    REQUIRE(std::size(obj.rate_limits) == 1);
  };
  WSAPIParserTester<value_type>::dispatch(helper, message, 8192, 2);
}
